name: weather_forecast
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  bloc: ^8.0.1
  flutter_bloc: ^8.1.0
  dropdown_button2: ^1.9.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  date_time_picker: ^2.1.0
  flutter_native_splash: ^2.2.15

flutter_native_splash:
  color: "#4b4b4b"
  image: assets/480_Color_gris.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/languages/
    - assets/icons/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

  uses-material-design: true
